name: extract-jdk-version
description: extract-jdk-version from pom.xml

outputs:
  version:
    description: Extracted jdk version
    value: ${{ steps.extract.outputs.version }}

runs:
  using: composite
  steps:
    - name: Extract JDK Version
      id: extract
      shell: bash
      run: |
        VERSION=$(grep -m 1 "<java.version>" "pom.xml" | sed 's/.*<java.version>\(.*\)<\/java.version>.*/\1/' | tr -d '\n\r' | xargs)
        echo "version=$VERSION" >> $GITHUB_OUTPUT